# **Module 21: Deep Learning - Alphabet Soup**

## Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pandas as pd
import tensorflow as tf

# Read the charity_data.csv.

#GitHub link to the CSV file
url = 'https://raw.githubusercontent.com/WayBurke/deep-learning-challenge/main/Resources/charity_data.csv'

application_df = pd.read_csv(url)
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.

application_df= application_df.drop(['EIN','NAME'],axis =1)
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [ ]:
# Determine the number of unique values in each column.

application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts for binning

app_type_valueCount = application_df['APPLICATION_TYPE'].value_counts()
app_type_valueCount

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`

application_types_to_replace = list(app_type_valueCount[app_type_valueCount < 500].index)


# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")


# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts for binning

classification_list = application_df['CLASSIFICATION'].value_counts()
classification_list

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1

classification_list[classification_list>1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`

classifications_to_replace = list(classification_list[classification_list <900].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
# One-hot encoding the entire dataframe

application_dummies = pd.get_dummies(application_df)
application_dummies

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [ ]:
# Split our preprocessed data into our features and target arrays
y = application_dummies.IS_SUCCESSFUL.values
X = application_dummies.drop(columns="IS_SUCCESSFUL").values


# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  80
hidden_nodes_layer2 = 30

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, activation="relu", input_dim=number_input_features))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                3520

 dense_1 (Dense)             (None, 30)                2430

 dense_2 (Dense)             (None, 1)                 31

=================================================================
Total params: 5,981
Trainable params: 5,981
Non-trainable params: 0
_________________________________________________________________

In [ ]:
# Compile the model

nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [ ]:
import os
#Create for folder callbacks
os.makedirs('saved_models/', exist_ok=True)

#File Path for checkpoint/callbacks
chk_point_path = "saved_models/weights_epoch{epoch:2d}.hdf5"

#Creating/Defining the Callback


save_callback = tf.keras.callbacks.ModelCheckpoint(
    chk_point_path,
    save_weights_only=True, 
    monitor ='accuracy',
    verbose =1,
    save_freq='epoch',
    save_best_only = True
)

In [ ]:
# Train the model

fit_model = nn.fit(X_train_scaled, y_train, epochs=100, callbacks=[save_callback])

Epoch 1/100
782/804 [============================>.] - ETA: 0s - loss: 0.5733 - accuracy: 0.7205
Epoch 1: accuracy improved from -inf to 0.72084, saving model to saved_models/weights_epoch 1.hdf5
804/804 [==============================] - 2s 2ms/step - loss: 0.5725 - accuracy: 0.7208
Epoch 2/100
801/804 [============================>.] - ETA: 0s - loss: 0.5557 - accuracy: 0.7290
Epoch 2: accuracy improved from 0.72084 to 0.72920, saving model to saved_models/weights_epoch 2.hdf5
804/804 [==============================] - 2s 2ms/step - loss: 0.5558 - accuracy: 0.7292
Epoch 3/100
802/804 [============================>.] - ETA: 0s - loss: 0.5523 - accuracy: 0.7315
Epoch 3: accuracy improved from 0.72920 to 0.73126, saving model to saved_models/weights_epoch 3.hdf5
804/804 [==============================] - 2s 2ms/step - loss: 0.5525 - accuracy: 0.7313
Epoch 4/100
802/804 [============================>.] - ETA: 0s - loss: 0.5511 - accuracy: 0.7316
Epoch 4: accuracy improved from 0.73126 to 0.73157, saving model to saved_models/weights_epoch 4.hdf5
804/804 [==============================] - 2s 2ms/step - loss: 0.5512 - accuracy: 0.7316
Epoch 5/100
793/804 [============================>.] - ETA: 0s - loss: 0.5496 - accuracy: 0.7338
Epoch 5: accuracy improved from 0.73157 to 0.73375, saving model to saved_models/weights_epoch 5.hdf5
804/804 [==============================] - 2s 2ms/step - loss: 0.5495 - accuracy: 0.7338
Epoch 6/100
780/804 [============================>.] - ETA: 0s - loss: 0.5480 - accuracy: 0.7339
Epoch 6: accuracy did not improve from 0.73375
804/804 [==============================] - 1s 2ms/step - loss: 0.5485 - accuracy: 0.7332
Epoch 7/100
781/804 [============================>.] - ETA: 0s - loss: 0.5475 - accuracy: 0.7349
Epoch 7: accuracy improved from 0.73375 to 0.73422, saving model to saved_models/weights_epoch 7.hdf5
804/804 [==============================] - 2s 2ms/step - loss: 0.5484 - accuracy: 0.7342
Epoch 8/100
789/804 [============================>.] - ETA: 0s - loss: 0.5468 - accuracy: 0.7348
Epoch 8: accuracy improved from 0.73422 to 0.73449, saving model to saved_models/weights_epoch 8.hdf5
804/804 [==============================] - 2s 2ms/step - loss: 0.5469 - accuracy: 0.7345
Epoch 9/100
801/804 [============================>.] - ETA: 0s - loss: 0.5479 - accuracy: 0.7340
Epoch 9: accuracy did not improve from 0.73449
804/804 [==============================] - 2s 2ms/step - loss: 0.5477 - accuracy: 0.7342
Epoch 10/100
777/804 [===========================>..] - ETA: 0s - loss: 0.5460 - accuracy: 0.7343
Epoch 10: accuracy did not improve from 0.73449
804/804 [==============================] - 2s 2ms/step - loss: 0.5467 - accuracy: 0.7337
Epoch 11/100
801/804 [============================>.] - ETA: 0s - loss: 0.5460 - accuracy: 0.7346
Epoch 11: accuracy improved from 0.73449 to 0.73461, saving model to saved_models/weights_epoch11.hdf5
804/804 [==============================] - 2s 2ms/step - loss: 0.5461 - accuracy: 0.7346
Epoch 12/100
780/804 [============================>.] - ETA: 0s - loss: 0.5457 - accuracy: 0.7355
Epoch 12: accuracy improved from 0.73461 to 0.73538, saving model to saved_models/weights_epoch12.hdf5
804/804 [==============================] - 1s 2ms/step - loss: 0.5455 - accuracy: 0.7354
Epoch 13/100
782/804 [============================>.] - ETA: 0s - loss: 0.5451 - accuracy: 0.7353
Epoch 13: accuracy did not improve from 0.73538
804/804 [==============================] - 2s 2ms/step - loss: 0.5453 - accuracy: 0.7351
Epoch 14/100
781/804 [============================>.] - ETA: 0s - loss: 0.5441 - accuracy: 0.7368
Epoch 14: accuracy improved from 0.73538 to 0.73667, saving model to saved_models/weights_epoch14.hdf5
804/804 [==============================] - 2s 2ms/step - loss: 0.5445 - accuracy: 0.7367
Epoch 15/100
778/804 [============================>.] - ETA: 0s - loss: 0.5448 - accuracy: 0.7355
Epoch 15: accuracy did not improve from 0.73667
804/804 [==============================] - 1s 2ms/step - loss: 0.5447 - accuracy: 0.7356
Epoch 16/100
794/804 [============================>.] - ETA: 0s - loss: 0.5434 - accuracy: 0.7372
Epoch 16: accuracy improved from 0.73667 to 0.73674, saving model to saved_models/weights_epoch16.hdf5
804/804 [==============================] - 2s 2ms/step - loss: 0.5439 - accuracy: 0.7367
Epoch 17/100
784/804 [============================>.] - ETA: 0s - loss: 0.5443 - accuracy: 0.7356
Epoch 17: accuracy did not improve from 0.73674
804/804 [==============================] - 2s 2ms/step - loss: 0.5443 - accuracy: 0.7357
Epoch 18/100
783/804 [============================>.] - ETA: 0s - loss: 0.5431 - accuracy: 0.7367
Epoch 18: accuracy did not improve from 0.73674
804/804 [==============================] - 2s 2ms/step - loss: 0.5436 - accuracy: 0.7364
Epoch 19/100
801/804 [============================>.] - ETA: 0s - loss: 0.5435 - accuracy: 0.7370
Epoch 19: accuracy improved from 0.73674 to 0.73705, saving model to saved_models/weights_epoch19.hdf5
804/804 [==============================] - 2s 2ms/step - loss: 0.5434 - accuracy: 0.7371
Epoch 20/100
778/804 [============================>.] - ETA: 0s - loss: 0.5424 - accuracy: 0.7376
Epoch 20: accuracy did not improve from 0.73705
804/804 [==============================] - 2s 2ms/step - loss: 0.5432 - accuracy: 0.7361
Epoch 21/100
785/804 [============================>.] - ETA: 0s - loss: 0.5427 - accuracy: 0.7372
Epoch 21: accuracy improved from 0.73705 to 0.73721, saving model to saved_models/weights_epoch21.hdf5
804/804 [==============================] - 2s 2ms/step - loss: 0.5429 - accuracy: 0.7372
Epoch 22/100
786/804 [============================>.] - ETA: 0s - loss: 0.5422 - accuracy: 0.7375
Epoch 22: accuracy improved from 0.73721 to 0.73760, saving model to saved_models/weights_epoch22.hdf5
804/804 [==============================] - 2s 2ms/step - loss: 0.5422 - accuracy: 0.7376
Epoch 23/100
798/804 [============================>.] - ETA: 0s - loss: 0.5429 - accuracy: 0.7372
Epoch 23: accuracy did not improve from 0.73760
804/804 [==============================] - 2s 2ms/step - loss: 0.5425 - accuracy: 0.7375
Epoch 24/100
784/804 [============================>.] - ETA: 0s - loss: 0.5429 - accuracy: 0.7363
Epoch 24: accuracy did not improve from 0.73760
804/804 [==============================] - 2s 2ms/step - loss: 0.5425 - accuracy: 0.7367
Epoch 25/100
786/804 [============================>.] - ETA: 0s - loss: 0.5417 - accuracy: 0.7379
Epoch 25: accuracy did not improve from 0.73760
804/804 [==============================] - 2s 2ms/step - loss: 0.5418 - accuracy: 0.7375
Epoch 26/100
793/804 [============================>.] - ETA: 0s - loss: 0.5415 - accuracy: 0.7374
Epoch 26: accuracy did not improve from 0.73760
804/804 [==============================] - 2s 2ms/step - loss: 0.5422 - accuracy: 0.7371
Epoch 27/100
790/804 [============================>.] - ETA: 0s - loss: 0.5421 - accuracy: 0.7387
Epoch 27: accuracy improved from 0.73760 to 0.73838, saving model to saved_models/weights_epoch27.hdf5
804/804 [==============================] - 2s 2ms/step - loss: 0.5422 - accuracy: 0.7384
Epoch 28/100
803/804 [============================>.] - ETA: 0s - loss: 0.5420 - accuracy: 0.7381
Epoch 28: accuracy did not improve from 0.73838
804/804 [==============================] - 2s 2ms/step - loss: 0.5419 - accuracy: 0.7381
Epoch 29/100
782/804 [============================>.] - ETA: 0s - loss: 0.5403 - accuracy: 0.7386
Epoch 29: accuracy did not improve from 0.73838
804/804 [==============================] - 1s 2ms/step - loss: 0.5412 - accuracy: 0.7382
Epoch 30/100
786/804 [============================>.] - ETA: 0s - loss: 0.5412 - accuracy: 0.7386
Epoch 30: accuracy did not improve from 0.73838
804/804 [==============================] - 1s 2ms/step - loss: 0.5415 - accuracy: 0.7383
Epoch 31/100
783/804 [============================>.] - ETA: 0s - loss: 0.5409 - accuracy: 0.7377
Epoch 31: accuracy did not improve from 0.73838
804/804 [==============================] - 2s 2ms/step - loss: 0.5411 - accuracy: 0.7376
Epoch 32/100
797/804 [============================>.] - ETA: 0s - loss: 0.5406 - accuracy: 0.7388
Epoch 32: accuracy improved from 0.73838 to 0.73853, saving model to saved_models/weights_epoch32.hdf5
804/804 [==============================] - 2s 3ms/step - loss: 0.5409 - accuracy: 0.7385
Epoch 33/100
801/804 [============================>.] - ETA: 0s - loss: 0.5405 - accuracy: 0.7379
Epoch 33: accuracy did not improve from 0.73853
804/804 [==============================] - 2s 2ms/step - loss: 0.5406 - accuracy: 0.7379
Epoch 34/100
801/804 [============================>.] - ETA: 0s - loss: 0.5413 - accuracy: 0.7379
Epoch 34: accuracy did not improve from 0.73853
804/804 [==============================] - 1s 2ms/step - loss: 0.5412 - accuracy: 0.7379
Epoch 35/100
790/804 [============================>.] - ETA: 0s - loss: 0.5404 - accuracy: 0.7382
Epoch 35: accuracy did not improve from 0.73853
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7382
Epoch 36/100
799/804 [============================>.] - ETA: 0s - loss: 0.5407 - accuracy: 0.7390
Epoch 36: accuracy improved from 0.73853 to 0.73900, saving model to saved_models/weights_epoch36.hdf5
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7390
Epoch 37/100
797/804 [============================>.] - ETA: 0s - loss: 0.5407 - accuracy: 0.7394
Epoch 37: accuracy improved from 0.73900 to 0.73947, saving model to saved_models/weights_epoch37.hdf5
804/804 [==============================] - 2s 3ms/step - loss: 0.5404 - accuracy: 0.7395
Epoch 38/100
792/804 [============================>.] - ETA: 0s - loss: 0.5404 - accuracy: 0.7384
Epoch 38: accuracy did not improve from 0.73947
804/804 [==============================] - 2s 2ms/step - loss: 0.5404 - accuracy: 0.7384
Epoch 39/100
780/804 [============================>.] - ETA: 0s - loss: 0.5402 - accuracy: 0.7381
Epoch 39: accuracy did not improve from 0.73947
804/804 [==============================] - 2s 2ms/step - loss: 0.5402 - accuracy: 0.7385
Epoch 40/100
778/804 [============================>.] - ETA: 0s - loss: 0.5398 - accuracy: 0.7391
Epoch 40: accuracy did not improve from 0.73947
804/804 [==============================] - 2s 2ms/step - loss: 0.5399 - accuracy: 0.7388
Epoch 41/100
784/804 [============================>.] - ETA: 0s - loss: 0.5396 - accuracy: 0.7402
Epoch 41: accuracy improved from 0.73947 to 0.74001, saving model to saved_models/weights_epoch41.hdf5
804/804 [==============================] - 2s 2ms/step - loss: 0.5398 - accuracy: 0.7400
Epoch 42/100
782/804 [============================>.] - ETA: 0s - loss: 0.5400 - accuracy: 0.7386
Epoch 42: accuracy did not improve from 0.74001
804/804 [==============================] - 2s 2ms/step - loss: 0.5399 - accuracy: 0.7389
Epoch 43/100
795/804 [============================>.] - ETA: 0s - loss: 0.5401 - accuracy: 0.7390
Epoch 43: accuracy did not improve from 0.74001
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7390
Epoch 44/100
786/804 [============================>.] - ETA: 0s - loss: 0.5389 - accuracy: 0.7396
Epoch 44: accuracy did not improve from 0.74001
804/804 [==============================] - 2s 2ms/step - loss: 0.5396 - accuracy: 0.7391
Epoch 45/100
792/804 [============================>.] - ETA: 0s - loss: 0.5387 - accuracy: 0.7393
Epoch 45: accuracy did not improve from 0.74001
804/804 [==============================] - 2s 2ms/step - loss: 0.5391 - accuracy: 0.7391
Epoch 46/100
789/804 [============================>.] - ETA: 0s - loss: 0.5395 - accuracy: 0.7396
Epoch 46: accuracy did not improve from 0.74001
804/804 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7395
Epoch 47/100
797/804 [============================>.] - ETA: 0s - loss: 0.5395 - accuracy: 0.7389
Epoch 47: accuracy did not improve from 0.74001
804/804 [==============================] - 2s 2ms/step - loss: 0.5394 - accuracy: 0.7391
Epoch 48/100
800/804 [============================>.] - ETA: 0s - loss: 0.5394 - accuracy: 0.7391
Epoch 48: accuracy did not improve from 0.74001
804/804 [==============================] - 2s 2ms/step - loss: 0.5394 - accuracy: 0.7390
Epoch 49/100
795/804 [============================>.] - ETA: 0s - loss: 0.5400 - accuracy: 0.7393
Epoch 49: accuracy did not improve from 0.74001
804/804 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7393
Epoch 50/100
787/804 [============================>.] - ETA: 0s - loss: 0.5390 - accuracy: 0.7395
Epoch 50: accuracy did not improve from 0.74001
804/804 [==============================] - 2s 2ms/step - loss: 0.5390 - accuracy: 0.7395
Epoch 51/100
786/804 [============================>.] - ETA: 0s - loss: 0.5387 - accuracy: 0.7395
Epoch 51: accuracy did not improve from 0.74001
804/804 [==============================] - 2s 2ms/step - loss: 0.5394 - accuracy: 0.7387
Epoch 52/100
776/804 [===========================>..] - ETA: 0s - loss: 0.5390 - accuracy: 0.7398
Epoch 52: accuracy did not improve from 0.74001
804/804 [==============================] - 2s 2ms/step - loss: 0.5390 - accuracy: 0.7397
Epoch 53/100
787/804 [============================>.] - ETA: 0s - loss: 0.5388 - accuracy: 0.7397
Epoch 53: accuracy did not improve from 0.74001
804/804 [==============================] - 2s 2ms/step - loss: 0.5390 - accuracy: 0.7396
Epoch 54/100
801/804 [============================>.] - ETA: 0s - loss: 0.5387 - accuracy: 0.7404
Epoch 54: accuracy improved from 0.74001 to 0.74020, saving model to saved_models/weights_epoch54.hdf5
804/804 [==============================] - 2s 2ms/step - loss: 0.5388 - accuracy: 0.7402
Epoch 55/100
793/804 [============================>.] - ETA: 0s - loss: 0.5381 - accuracy: 0.7386
Epoch 55: accuracy did not improve from 0.74020
804/804 [==============================] - 2s 2ms/step - loss: 0.5381 - accuracy: 0.7388
Epoch 56/100
796/804 [============================>.] - ETA: 0s - loss: 0.5394 - accuracy: 0.7398
Epoch 56: accuracy did not improve from 0.74020
804/804 [==============================] - 2s 2ms/step - loss: 0.5392 - accuracy: 0.7400
Epoch 57/100
790/804 [============================>.] - ETA: 0s - loss: 0.5391 - accuracy: 0.7385
Epoch 57: accuracy did not improve from 0.74020
804/804 [==============================] - 2s 2ms/step - loss: 0.5388 - accuracy: 0.7386
Epoch 58/100
804/804 [==============================] - ETA: 0s - loss: 0.5385 - accuracy: 0.7399
Epoch 58: accuracy did not improve from 0.74020
804/804 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7399
Epoch 59/100
797/804 [============================>.] - ETA: 0s - loss: 0.5379 - accuracy: 0.7400
Epoch 59: accuracy did not improve from 0.74020
804/804 [==============================] - 2s 2ms/step - loss: 0.5384 - accuracy: 0.7398
Epoch 60/100
803/804 [============================>.] - ETA: 0s - loss: 0.5385 - accuracy: 0.7398
Epoch 60: accuracy did not improve from 0.74020
804/804 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7398
Epoch 61/100
779/804 [============================>.] - ETA: 0s - loss: 0.5382 - accuracy: 0.7398
Epoch 61: accuracy did not improve from 0.74020
804/804 [==============================] - 2s 2ms/step - loss: 0.5381 - accuracy: 0.7398
Epoch 62/100
795/804 [============================>.] - ETA: 0s - loss: 0.5387 - accuracy: 0.7395
Epoch 62: accuracy did not improve from 0.74020
804/804 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7398
Epoch 63/100
802/804 [============================>.] - ETA: 0s - loss: 0.5385 - accuracy: 0.7395
Epoch 63: accuracy did not improve from 0.74020
804/804 [==============================] - 2s 2ms/step - loss: 0.5384 - accuracy: 0.7395
Epoch 64/100
789/804 [============================>.] - ETA: 0s - loss: 0.5370 - accuracy: 0.7408
Epoch 64: accuracy improved from 0.74020 to 0.74024, saving model to saved_models/weights_epoch64.hdf5
804/804 [==============================] - 2s 2ms/step - loss: 0.5378 - accuracy: 0.7402
Epoch 65/100
783/804 [============================>.] - ETA: 0s - loss: 0.5387 - accuracy: 0.7397
Epoch 65: accuracy did not improve from 0.74024
804/804 [==============================] - 2s 2ms/step - loss: 0.5383 - accuracy: 0.7400
Epoch 66/100
788/804 [============================>.] - ETA: 0s - loss: 0.5380 - accuracy: 0.7399
Epoch 66: accuracy improved from 0.74024 to 0.74028, saving model to saved_models/weights_epoch66.hdf5
804/804 [==============================] - 2s 2ms/step - loss: 0.5377 - accuracy: 0.7403
Epoch 67/100
790/804 [============================>.] - ETA: 0s - loss: 0.5375 - accuracy: 0.7405
Epoch 67: accuracy did not improve from 0.74028
804/804 [==============================] - 2s 2ms/step - loss: 0.5378 - accuracy: 0.7403
Epoch 68/100
790/804 [============================>.] - ETA: 0s - loss: 0.5373 - accuracy: 0.7401
Epoch 68: accuracy did not improve from 0.74028
804/804 [==============================] - 2s 2ms/step - loss: 0.5377 - accuracy: 0.7399
Epoch 69/100
797/804 [============================>.] - ETA: 0s - loss: 0.5377 - accuracy: 0.7403
Epoch 69: accuracy did not improve from 0.74028
804/804 [==============================] - 2s 2ms/step - loss: 0.5376 - accuracy: 0.7402
Epoch 70/100
800/804 [============================>.] - ETA: 0s - loss: 0.5380 - accuracy: 0.7398
Epoch 70: accuracy did not improve from 0.74028
804/804 [==============================] - 2s 2ms/step - loss: 0.5376 - accuracy: 0.7402
Epoch 71/100
778/804 [============================>.] - ETA: 0s - loss: 0.5376 - accuracy: 0.7400
Epoch 71: accuracy did not improve from 0.74028
804/804 [==============================] - 2s 2ms/step - loss: 0.5378 - accuracy: 0.7401
Epoch 72/100
782/804 [============================>.] - ETA: 0s - loss: 0.5365 - accuracy: 0.7413
Epoch 72: accuracy improved from 0.74028 to 0.74059, saving model to saved_models/weights_epoch72.hdf5
804/804 [==============================] - 2s 2ms/step - loss: 0.5369 - accuracy: 0.7406
Epoch 73/100
785/804 [============================>.] - ETA: 0s - loss: 0.5368 - accuracy: 0.7403
Epoch 73: accuracy did not improve from 0.74059
804/804 [==============================] - 2s 2ms/step - loss: 0.5373 - accuracy: 0.7400
Epoch 74/100
783/804 [============================>.] - ETA: 0s - loss: 0.5369 - accuracy: 0.7399
Epoch 74: accuracy did not improve from 0.74059
804/804 [==============================] - 2s 2ms/step - loss: 0.5372 - accuracy: 0.7396
Epoch 75/100
780/804 [============================>.] - ETA: 0s - loss: 0.5376 - accuracy: 0.7402
Epoch 75: accuracy improved from 0.74059 to 0.74067, saving model to saved_models/weights_epoch75.hdf5
804/804 [==============================] - 2s 2ms/step - loss: 0.5372 - accuracy: 0.7407
Epoch 76/100
794/804 [============================>.] - ETA: 0s - loss: 0.5372 - accuracy: 0.7402
Epoch 76: accuracy did not improve from 0.74067
804/804 [==============================] - 2s 2ms/step - loss: 0.5375 - accuracy: 0.7400
Epoch 77/100
780/804 [============================>.] - ETA: 0s - loss: 0.5366 - accuracy: 0.7403
Epoch 77: accuracy did not improve from 0.74067
804/804 [==============================] - 2s 2ms/step - loss: 0.5372 - accuracy: 0.7397
Epoch 78/100
804/804 [==============================] - ETA: 0s - loss: 0.5371 - accuracy: 0.7401
Epoch 78: accuracy did not improve from 0.74067
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7401
Epoch 79/100
802/804 [============================>.] - ETA: 0s - loss: 0.5369 - accuracy: 0.7403
Epoch 79: accuracy did not improve from 0.74067
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7402
Epoch 80/100
781/804 [============================>.] - ETA: 0s - loss: 0.5365 - accuracy: 0.7408

In [ ]:
# Evaluate the model using the test data

model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5563 - accuracy: 0.7254 - 499ms/epoch - 2ms/step
Loss: 0.5562915802001953, Accuracy: 0.7253644466400146

In [ ]:
# Export our model to HDF5 file

#Create for folder final Model
os.makedirs('h5_models/', exist_ok=True)

nn.save('h5_models/AlphabetSoupCharity.h5')